version: '3'

services:

  website:
    container_name: website
    restart: always
    build: ./website
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:app
    environment:
      PYTHONUNBUFFERED: 1


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - website
