version: '3.6'
services:

  nginx:
        build: ./services/nginx
        ports:
                - 1337:80
        depends_on:
                 - client
  client:
      volumes:
        - .:/app
      build:
        context: .
        dockerfile: Dockerfile
      command: gunicorn --bind 0.0.0.0:9084 manage:app
      container_name: website
      expose:
         - 9084

      hostname: website
      command: python3 server.py
      networks:
        - server
      restart: always


networks:
  server:
    external: true
